---
server:
    install: '1'
    packages: [vim, htop, git]
    timezone: Australia/Sydney
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.35.12, memory: '512', sharedfolder: ./app/, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: l4d.tv.vagrant
    vhostpath: /etc/nginx/sites-available
    vhostenabledpath: /etc/nginx/sites-enabled
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-fpm, php5-gd, php5-xdebug, php5-mysql]
composer:
    install: '1'
app:
    www: /vagrant/app
    backend: backend/web
    frontend: frontend/web
    hostname:
        frontend: www.l4d.tv.vagrant
        backend: admin.l4d.tv.vagrant
    db:
        test:
            database: db_test
            user: db
            password: password
        main:
          database: "{{ mysql.database }}"
          user: "{{ mysql.user }}"
          password: "{{ mysql.password }}"